[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
