[phases.setup]
nixPkgs = ['nodejs', 'python311']

[phases.install]
cmds = [
    'cd frontend && npm ci',
    'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT'
